# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextEditorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextEditor(object):
    def setupUi(self, TextEditor):
        TextEditor.setObjectName("TextEditor")
        TextEditor.resize(460, 410)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/notepad-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TextEditor.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(TextEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEdit.setObjectName("TextEdit")
        self.verticalLayout.addWidget(self.TextEdit)
        TextEditor.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(TextEditor)
        self.toolBar.setObjectName("toolBar")
        TextEditor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(TextEditor)
        self.statusBar.setObjectName("statusBar")
        TextEditor.setStatusBar(self.statusBar)

        self.retranslateUi(TextEditor)
        QtCore.QMetaObject.connectSlotsByName(TextEditor)

    def retranslateUi(self, TextEditor):
        _translate = QtCore.QCoreApplication.translate
        TextEditor.setWindowTitle(_translate("TextEditor", "Текстовый редактор"))
        self.toolBar.setWindowTitle(_translate("TextEditor", "toolBar"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TextEditor = QtWidgets.QMainWindow()
    ui = Ui_TextEditor()
    ui.setupUi(TextEditor)
    TextEditor.show()
    sys.exit(app.exec_())
